### PR TITLE
MTKo | Initial commit of the Xcode project

### PR DESCRIPTION
**Pull request by MyatThuKo**
This is the initial barebone Xcode project. 

[Asana ticket](https://app.asana.com/0/1204171546585013/1204277107116356/f)

### CODE REVIEW

**Comment by cyanChill** [comment]
Looks good; seems like we're going to use Storyboard instead of SwiftUI as the interface for the IOS app so I'll look into it to maybe provide some help with connecting the Firebase Cloud Functions stuff with the IOS app.

**Comment by MyatThuKo** [comment]
> Looks good; seems like we're going to use SwiftUI as the interface for the IOS app so I'll look into it to maybe provide some help with connecting the Firebase Cloud Functions stuff with the IOS app.

We're going to use SwiftUI and not the storyboard.

**Comment by cyanChill** [comment]
Yea, I edited my comment after looking a bit closer

**Review by cyanChill — APPROVED** [review]
Looks good and standard for a starter Swift Xcode project

**Pull request merged**
