### PR TITLE
Initial Backend Functionalities w/ Tests

### PR DESCRIPTION
**Pull request by cyanChill**
This includes:
1. A trigger to create a `user` document in the `users` database when a user signs up.
2. An onCall function to create a `flashcard` (set) document in the `flashcards` database and update the `user` document of the user who created the flashcard set to have a reference to it.
3. An `utils.js` file containing functions to help with input validation.

In addition, there is test coverage on all of these new functions/features (which are passing when tested locally) along with updated setup documentation.

Code review done in Discord by John.

### CODE REVIEW

**Comment by j2kb-gs** [comment]
Reviewed!
- great code structure 
- nice job thinking ahead
I was thinking maybe we could create a "controllers" folder to hold files like user.js and flashcard.js otherwise our functions folder might get kinda hard to navigate

**Comment by cyanChill** [comment]
Created a `src` folder to contain `utils.js` and a `controllers` folder to contain our Firebase functions and such.

**Comment by j2kb-gs** [comment]
Nice

**Comment by cyanChill** [comment]
Don't close; wait for review & merge

**Comment by j2kb-gs** [comment]
ok

**Review by j2kb-gs — APPROVED** [review]
approved

**Pull request merged**
