### PR TITLE
Mtko | Signup, Login, Reset password screens

### PR DESCRIPTION
**Pull request by MyatThuKo**
## Asana & Figma

- [Login/Signup Screens](https://app.asana.com/0/1204171546585013/1204277107116357/f)
- [Reset password Screen](https://app.asana.com/0/0/1204501798274709/f) 
- [Figma](https://www.figma.com/file/QZWGuUWuXL5MNRt5x64Szj/FlashCard-App?node-id=18-4&t=9nvdzwfpilvE69KU-4)

## Description

- Add hard-coded login, sign up, and reset password screens 
- Set the default theme to the dark mode 

## Screenshots & Video

<details>
<summary>View them here</summary>

| Signup | Login | Reset Password | 
| :---: | :--: | :--: |
|  |     |  

<video src="https://user-images.githubusercontent.com/48729479/235335542-a320f277-3348-46d1-a743-d5f1bb721ca9.mov" /> 

</details>

## Type of Change

- [x} Adding new features: This involves creating a new capability, such as a screen with multiple entry points. It is usually hidden behind a feature flag to avoid disrupting existing.
- [ ] Refactoring: This includes tasks like refactoring or modifying existing view controllers, which may affect how the app behaves.
- [ ] Squashing bugs: This type of change resolves an issue without introducing new problems.

## Risk
- Since these screens are all hard-coded, low risk.

### CODE REVIEW

**Review by cyanChill — APPROVED** [review]
Testing the hard-coded screens on my MacBook seems to work (albeit with a small hiccup with setting it up as a device wasn't set up from initializing the XCode project, causing errors to show up that were fixed after selecting a device):
- Signup screen seems to work (doesn't actually signs up the user for now) and returns an error if the passwords aren't the same.
  - One potential problem is that there's currently no min-length to the password (along with no validation on email that it is an email).
- Reset password screen seems to work - after inputting an email, it returns a response saying that a reset link has been seen (as a mockup)
  - Again, validation that the input is an email is something that should be added.
- Login screen returns a response when signing in with values (no validation for now)

Overall, general auth-flow screens are done with hardcoded values (just validation needs to be added)

**Comment by MyatThuKo** [comment]
> Testing the hard-coded screens on my MacBook seems to work (albeit with a small hiccup with setting it up as a device wasn't set up from initializing the XCode project, causing errors to show up that were fixed after selecting a device):
> 
> * Signup screen seems to work (doesn't actually signs up the user for now) and returns an error if the passwords aren't the same.
>   
>   * One potential problem is that there's currently no min-length to the password (along with no validation on email that it is an email).
> * Reset password screen seems to work - after inputting an email, it returns a response saying that a reset link has been seen (as a mockup)
>   
>   * Again, validation that the input is an email is something that should be added.
> * Login screen returns a response when signing in with values (no validation for now)
> 
> Overall, general auth-flow screens are done with hardcoded values (just validation needs to be added)

Add some validation functions to all three screens but still hard-coded values.

**Comment by j2kb-gs** [comment]
I don't know if the steps are somewhere else.. but how do I get to test the code on my machine? I'm getting some errors..

**Comment by cyanChill** [comment]
I just went to the [`wip-mtko-signup-and-login-screen`](https://github.com/MyatThuKo/CSc456-FlashCardApp-Final-Project/tree/wip-mtko-signup-and-login-screen) branch and downloaded the zip.

Then in Xcode, choose `Open a project or file` and select the `StudySwift.xcodeproj` folder in `StudySwift/StudySwift.xcodeproj`.

You have to switch the `Team` option in the project to `None` to get it to work (since it's currently set to Myat's team and it'll throw an error there).

**Pull request merged**
